=== hirosystems/stacks-blockchain-api/docs/api/bns/name-querying/bns-get-subdomain-at-tx-response.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "bns-get-subdomain-at-tx",
  "title": "BnsGetSubdomainAtTx",
  "description": "Fetches the list of subdomain operations processed by a given transaction. The returned array includes subdomain operations that have not yet been accepted as part of any subdomainâ€™s history (checkable via the accepted field). If the given transaction ID does not correspond to a Stacks transaction that introduced new subdomain operations, and empty array will be returned.",
  "required": [
    "accepted",
    "block_height",
    "domain",
    "fully_qualified_subdomain",
    "missing",
    "owner",
    "parent_zonefile_hash",
    "parent_zonefile_index",
    "resolver",
    "sequence",
    "signature",
    "txid",
    "zonefile_hash",
    "zonefile_offset"
  ],
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "accepted": {
        "type": "integer",
        "minimum": 0,
        "maximum": 1
      },
      "block_height": { "type": "integer", "minimum": 0 },
      "domain": {
        "type": "string",
        "pattern": "^([a-z0-9\\-_.+]{3,37})$|^([a-z0-9\\-_.+]){3,37}$"
      },
      "fully_qualified_subdomain": {
        "type": "string",
        "pattern": "^([a-z0-9\\-_.+]{3,37}).([a-z0-9\\-_.+]{3,37})$"
      },
      "missing": { "type": "string" },
      "owner": {
        "type": "string",
        "pattern": "^([123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]+)$"
      },
      "parent_zonefile_hash": {
        "type": "string",
        "pattern": "^[0-9a-fA-F]{40}"
      },
      "parent_zonefile_index": {
        "type": "integer",
        "minimum": 0
      },
      "resolver": {
        "type": "string"
      },
      "sequence": {
        "type": "integer",
        "minimum": 0
      },
      "signature": {
        "type": "string"
      },
      "txid": {
        "type": "string",
        "pattern": "^[0-9a-fA-F]{64}"
      },
      "zonefile_hash": {
        "type": "string",
        "pattern": "^[0-9a-fA-F]{40}"
      },
      "zonefile_offset": {
        "type": "integer",
        "minimum": 0
      }
    }
  }
}

=== hirosystems/stacks-blockchain-api/api/bns/name-querying/bns-get-subdomain-at-tx-response.example.json
[
  {
    "accepted": 1,
    "block_height": 546199,
    "domain": "id.blockstack",
    "fully_qualified_subdomain": "nturl345.id.blockstack",
    "missing": "",
    "owner": "17Q8hcsxRLCk3ypJiGeXQv9tFK9GnHr5Ea",
    "parent_zonefile_hash": "58224144791919f6206251a9960a2dd5723b96b6",
    "parent_zonefile_index": 95780,
    "resolver": "https://registrar.blockstack.org",
    "sequence": 0,
    "signature": "None",
    "txid": "d04d708472ea3c147f50e43264efdb1535f71974053126dc4db67b3ac19d41fe",
    "zonefile_hash": "d3bdf1cf010aac3f21fac473e41450f5357e0817",
    "zonefile_offset": 0
  },
  {
    "accepted": 1,
    "block_height": 546199,
    "domain": "id.blockstack",
    "fully_qualified_subdomain": "dwerner1.id.blockstack",
    "missing": "",
    "owner": "17tFeKEBMUAAiHVsCgqKo8ccwYqq7aCn9X",
    "parent_zonefile_hash": "58224144791919f6206251a9960a2dd5723b96b6",
    "parent_zonefile_index": 95780,
    "resolver": "https://registrar.blockstack.org",
    "sequence": 0,
    "signature": "None",
    "txid": "d04d708472ea3c147f50e43264efdb1535f71974053126dc4db67b3ac19d41fe",
    "zonefile_hash": "ab79b1774fa7a4c5709b6ad4e5892fb7c0f79765",
    "zonefile_offset": 1
  }
]
