=== hirosystems/stacks-blockchain-api/docs/api/tokens/get-non-fungible-token-history.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "List of Non-Fungible Token history events",
  "title": "NonFungibleTokenHistoryEventList",
  "type": "object",
  "required": [
    "results",
    "limit",
    "offset",
    "total"
  ],
  "additionalProperties": false,
  "properties": {
    "limit": {
      "type": "integer",
      "maximum": 200,
      "description": "The number of events to return"
    },
    "offset": {
      "type": "integer",
      "description": "The number to events to skip (starting at `0`)"
    },
    "total": {
      "type": "integer",
      "description": "The number of events available"
    },
    "results": {
      "type": "array",
      "items": {
        "$ref": "../../entities/tokens/non-fungible-token-history-event.schema.json"
      }
    }
  }
}

=== hirosystems/stacks-blockchain-api/docs/api/address/get-address-assets.example.json
{
  "limit": 20,
  "offset": 0,
  "total": 0,
  "results": [
    {
      "event_index": 0,
      "event_type": "stx_asset",
      "tx_id": "0xb31df5a363dad31723324cb5e0eefa04d491519fd30827a521cbc830114aa50c",
      "asset": {
        "asset_event_type": "transfer",
        "sender": "STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6",
        "recipient": "ST2TJRHDHMYBQ417HFB0BDX430TQA5PXRX6495G1V",
        "amount": "500000"
      }
    }
  ]
}

=== hirosystems/stacks-blockchain-api/docs/api/stacking/get-pool-delegations.example.json
{
  "limit": 200,
  "offset": 0,
  "total": 2,
  "results": [
    {
      "stacker": "SPDGWQ60E1QXTC6E4VHKK0NG34EAX554WDFFFHMF",
      "pox_addr": "bc1qxhmdufsvnuaaaer4ynz88fspdsxq2h9e9cetdj",
      "amount_ustx": "2062697998",
      "burn_block_unlock_height": 781984,
      "block_height": 65917,
      "tx_id": "0x3c81cd26ed172a7e552ed245b8b290abefa4f82dfc610a0091ac91c2eed7f9e6"
    },
    {
      "stacker": "SP7RNXF7YBSS43TECXTHF7W1MAB221WWW8RKPGSN",
      "pox_addr": "1Di1YoMov6Ua3gPedfQz7TkP6iTLqbPUzi",
      "amount_ustx": "4815793194",
      "block_height": 65910,
      "tx_id": "0x1692cd26ed172a7e552ed245b8b290abefa4f82dfc610a0091ac91c2eed7f9e6"
    }
  ]
}

=== hirosystems/stacks-blockchain-api/docs/api/tokens/get-non-fungible-token-holdings.example.schema.json
{
	"limit": 50,
	"offset": 0,
	"total": 3,
	"results": [
		{
			"asset_identifier": "SP2X0TZ59D5SZ8ACQ6YMCHHNR2ZN51Z32E2CJ173.the-explorer-guild::The-Explorer-Guild",
			"value": {
				"hex": "0x0100000000000000000000000000000803",
				"repr": "u2051"
			},
			"tx_id": "0x12e6f88724d0e630de26c376f172cf1781e25435e2b4ee54d36a949b244e429c"
		},
		{
			"asset_identifier": "SP2BE8TZATXEVPGZ8HAFZYE5GKZ02X0YDKAN7ZTGW.arties::arties",
			"value": {
				"hex": "0x01000000000000000000000000000004f3",
				"repr": "u1267"
			},
			"tx_id": "0xddc464c5e20a78dc5ac351913e0d9b9cce76fc955cc4599e0cccad960998f130"
		},
		{
			"asset_identifier": "SP000000000000000000002Q6VF78.bns::names",
			"value": {
				"hex": "0x0c00000002046e616d65020000000672616661656c096e616d6573706163650200000003627463",
				"repr": "(tuple (name 0x72616661656c) (namespace 0x627463))"
			},
			"tx_id": "0x0153a41ed24a0e1d32f66ea98338df09f942571ca66359e28bdca79ccd0305cf"
		}
	]
}

=== hirosystems/stacks-blockchain-api/docs/api/address/get-v2-address-transactions.example.json
{
  "limit": 20,
  "offset": 0,
  "total": 2,
  "results": [
    {
      "tx": {
        "tx_id": "0x34d79c7cfc2fe525438736733e501a4bf0308a5556e3e080d1e2c0858aad7448",
        "tx_type": "contract_call",
        "nonce": 11,
        "fee_rate": "346",
        "sender_address": "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE",
        "sponsored": false,
        "post_condition_mode": "deny",
        "tx_status": "success",
        "block_hash": "0x13d1b4ad35c95bca209397420fb8af104d2929d91993ba056d7a1ca5470095f9",
        "block_height": 3246,
        "burn_block_time": 1613009951,
        "burn_block_time_iso": "2021-02-11T02:19:11.000Z",
        "canonical": true,
        "is_unanchored": false,
        "microblock_hash": "0x590a1bb1d7bcbeafce0a9fc8f8a69e369486192d14687fe95fbe4dc1c71d49df",
        "microblock_sequence": 5,
        "microblock_canonical": true,
        "tx_index": 1,
        "tx_result": {
          "hex": "0x0703",
          "repr": "(ok true)"
        },
        "post_conditions": [
          {
            "type": "stx",
            "condition_code": "sent_equal_to",
            "amount": "350",
            "principal": {
              "type_id": "principal_standard",
              "address": "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE"
            }
          }
        ],
        "contract_call": {
          "contract_id": "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.send-many-memo",
          "function_name": "send-many",
          "function_signature": "(define-public (send-many (recipients (list 200 (tuple (memo (buff 34)) (to principal) (ustx uint))))))",
          "function_args": [
            {
              "hex": "0x0b000000020c00000003046d656d6f020000000966697273746d656d6f02746f05168c031b2db5895ece0cdfbf76e0b0e8af67226a6f047573747801000000000000000000000000000000960c00000003046d656d6f020000000a7365636f6e646d656d6f02746f05168974da696d74a16d0955bc8e55720dfd39e789cf047573747801000000000000000000000000000000c8",
              "repr": "(list (tuple (memo 0x66697273746d656d6f) (to SP26066SDPP4NXKGCVYZQDR5GX2QPE8KADZ0YK2J7) (ustx u150)) (tuple (memo 0x7365636f6e646d656d6f) (to SP24Q9PK9DNTA2V89APY8WNBJ1QYKKSW9SWB04RJP) (ustx u200)))",
              "name": "recipients",
              "type": "(list 200 (tuple (memo (buff 34)) (to principal) (ustx uint)))"
            }
          ]
        },
        "events": [],
        "event_count": 4
      },
      "stx_sent": "696",
      "stx_received": "0",
      "events": {
        "stx": {
          "transfer": 2,
          "mint": 0,
          "burn": 0
        },
        "ft": {
          "transfer": 1,
          "mint": 0,
          "burn": 0
        },
        "nft": {
          "transfer": 1,
          "mint": 0,
          "burn": 0
        }
      }
    },
    {
      "tx": {
        "tx_id": "0x628045bff13658396277d618e9a3e4d468a4b3876eff4941d2f13ed88cd7abb7",
        "tx_type": "token_transfer",
        "nonce": 8,
        "fee_rate": "180",
        "sender_address": "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE",
        "sponsored": false,
        "post_condition_mode": "deny",
        "tx_status": "success",
        "block_hash": "0x2b8599696f64e2456c67b1ab5e63078f99d87bd1d903c37fdcfd73b1890a7551",
        "block_height": 1761,
        "burn_block_time": 1611968237,
        "burn_block_time_iso": "2021-01-30T00:57:17.000Z",
        "canonical": true,
        "is_unanchored": false,
        "microblock_hash": "",
        "microblock_sequence": 2147483647,
        "microblock_canonical": true,
        "tx_index": 2,
        "tx_result": {
          "hex": "0x0703",
          "repr": "(ok true)"
        },
        "token_transfer": {
          "recipient_address": "SPRSM0R2JZWBCZ39NQBARWTMX9TE99K3JK8D5KMX",
          "amount": "100000",
          "memo": "0x57656c636f6d6520746f20426f6f6d2e000000000000000000000000000000000000"
        },
        "events": [],
        "event_count": 1
      },
      "stx_sent": "100180",
      "stx_received": "0",
      "events": {
        "stx": {
          "transfer": 1,
          "mint": 0,
          "burn": 0
        },
        "ft": {
          "transfer": 0,
          "mint": 0,
          "burn": 0
        },
        "nft": {
          "transfer": 0,
          "mint": 0,
          "burn": 0
        }
      }
    }
  ]
}

=== hirosystems/stacks-blockchain-api/docs/api/address/get-address-transactions.example.json
{
  "limit": 20,
  "offset": 0,
  "total": 4989,
  "results": [
    {
      "tx_id": "0xb16077b94222bc1466396d30df13db460864e85ce929a20aae0a2ac80b31e4e2",
      "tx_status": "success",
      "tx_type": "coinbase",
      "fee_rate": "0",
      "sender_address": "ST2TJRHDHMYBQ417HFB0BDX430TQA5PXRX6495G1V",
      "sponsored": false,
      "post_condition_mode": "deny",
      "block_hash": "0x83f84f814c1b00ddb672d93b97d06c8326f76746d90a979c12b69e54beb73f69",
      "block_height": 5603,
      "burn_block_time": 1594335838,
      "canonical": true,
      "is_unanchored": false,
      "microblock_hash": "0x590a1bb1d7bcbeafce0a9fc8f8a69e369486192d14687fe95fbe4dc1c71d49df",
      "microblock_sequence": 5,
      "microblock_canonical": true,
      "tx_index": 0,
      "coinbase_payload": {
        "data": "0x0000000000000000000000000000000000000000000000000000000000000000"
      }
    }
  ]
}

=== hirosystems/stacks-blockchain-api/docs/api/address/get-address-transaction-events.example.json
{
  "limit": 20,
  "offset": 0,
  "total": 4,
  "results": [
    {
      "type": "stx",
      "event_index": 0,
      "data": {
        "type": "transfer",
        "amount": "200",
        "sender": "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE",
        "recipient": "SP24Q9PK9DNTA2V89APY8WNBJ1QYKKSW9SWB04RJP"
      }
    },
    {
      "type": "stx",
      "event_index": 1,
      "data": {
        "type": "transfer",
        "amount": "150",
        "sender": "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE",
        "recipient": "SP26066SDPP4NXKGCVYZQDR5GX2QPE8KADZ0YK2J7"
      }
    },
    {
      "type": "ft",
      "event_index": 5,
      "data": {
        "type": "transfer",
        "amount": "103",
        "asset_identifier": "SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-token::miamicoin",
        "sender": "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE",
        "recipient": "SP24Q9PK9DNTA2V89APY8WNBJ1QYKKSW9SWB04RJP"
      }
    },
    {
      "type": "nft",
      "event_index": 6,
      "data": {
        "type": "transfer",
        "asset_identifier": "SP497E7RX3233ATBS2AB9G4WTHB63X5PBSP5VGAQ.boom-nfts::boom",
        "value": { "hex": "0x00", "repr": "0" },
        "sender": "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE",
        "recipient": "SP24Q9PK9DNTA2V89APY8WNBJ1QYKKSW9SWB04RJP"
      }
    }
  ]
}

=== hirosystems/stacks-blockchain-api/api/transaction/get-mempool-transactions.example.json
{
  "limit": 96,
  "offset": 0,
  "total": 5,
  "results": [
    {
      "tx_id": "0xb31df5a363dad31723324cb5e0eefa04d491519fd30827a521cbc830114aa50c",
      "tx_status": "pending",
      "tx_type": "token_transfer",
      "receipt_time": 1598288370,
      "receipt_time_iso": "2020-08-24T16:59:30.000Z",
      "fee_rate": "180",
      "sender_address": "STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6",
      "sponsored": false,
      "post_condition_mode": "deny",
      "post_conditions": [],
      "anchor_mode": "any",
      "token_transfer": {
        "recipient_address": "ST1GY25DM8RZV4X15X07THRZ2C5NMWPGQWKFGV87F",
        "amount": "500000",
        "memo": "0x46617563657400000000000000000000000000000000000000000000000000000000"
      }
    },
    {
      "tx_id": "0x5bed8e3f801cb4e2c74d2815a092f7c1c6a35f2fce4a80c80ca70848d34cb395",
      "tx_status": "pending",
      "tx_type": "token_transfer",
      "receipt_time": 1598282326,
      "receipt_time_iso": "2020-08-24T15:18:46.000Z",
      "fee_rate": "180",
      "sender_address": "ST1PS1KF93VBY5A1JV7TM66KN046KP3E3761DBSAG",
      "sponsored": false,
      "post_condition_mode": "deny",
      "post_conditions": [],
      "anchor_mode": "any",
      "token_transfer": {
        "recipient_address": "ST2H33S8SEY27QKEKQKR6S5PECYPKY45CQYGGQR8X",
        "amount": "1000",
        "memo": "0x00000000000000000000000000000000000000000000000000000000000000000000"
      }
    },
    {
      "tx_id": "0x9916036fde08a207e581cdcabc18ff55469861cb81194ab0e3e7c9a02cd5a17c",
      "tx_status": "pending",
      "tx_type": "smart_contract",
      "receipt_time": 1598258958,
      "receipt_time_iso": "2020-08-24T08:49:18.000Z",
      "fee_rate": "2000",
      "sender_address": "ST2R1XSFXYHCSFE426HP45TTD8ZWV9XHX2SRP3XA8",
      "sponsored": false,
      "post_condition_mode": "deny",
      "post_conditions": [],
      "anchor_mode": "any",
      "smart_contract": {
        "contract_id": "ST2R1XSFXYHCSFE426HP45TTD8ZWV9XHX2SRP3XA8.test-loans-1",
        "source_code": "(define-data-var stx-loaned int 0)\n(define-data-var lockup-period int 0)\n(define-data-var stx-return int 0)\n(define-public (get-stx-return (stx uint) (months uint))\n    (ok\n        (begin\n            (var-set stx-loaned (to-int(stx))\n            (var-set lockup-period (to-int(months))\n            (calculate-stx-return)\n            (print (var-get stx-return))\n            (transfer-to-server)\n        )\n    )\n)\n(define-private (calculate-stx-return)\n    (ok\n        (begin\n            (var-set stx-return (- (+ (* (/ (* (var-get stx-loaned) 5) 100) (var-get lockup-period)) (var-get stx-loaned)) 5))\n        )\n    )\n)\n(define-private (transfer-to-server)\n  (begin\n    (unwrap-panic (stx-transfer? (to-uint (var-get stx-loaned)) tx-sender 'ST2R1XSFXYHCSFE426HP45TTD8ZWV9XHX2SRP3XA8))\n    (ok (to-uint (var-get stx-loaned)))\n  )\n)"
      }
    },
    {
      "tx_id": "0x871fb186c8d6ac6ede2822c71074d9884b593c0d7f2d0d6e8516e615484d7501",
      "tx_status": "pending",
      "tx_type": "smart_contract",
      "receipt_time": 1598230365,
      "receipt_time_iso": "2020-08-24T00:52:45.000Z",
      "fee_rate": "2000",
      "sender_address": "ST1FJGMWPGM1P7N0K3N9QEPZK5H1VDC5YWTVMEAZ1",
      "sponsored": false,
      "post_condition_mode": "deny",
      "post_conditions": [],
      "anchor_mode": "any",
      "smart_contract": {
        "contract_id": "ST1FJGMWPGM1P7N0K3N9QEPZK5H1VDC5YWTVMEAZ1.contract-hook-1598230358601",
        "source_code": ";; ## CUSTOM FUNCTION TO EXTRACT A SUBSTRING\n\n(define-read-only (subs (source (buff 10)) \n                        (start int) \n                        (end int))\n (begin\n  (unwrap-panic (if (and (<= 0 start) (<= start 10)) (ok 1) (err \"Out of bounds: start\")))\n  (unwrap-panic (if (and (<= 0 end) (<= end 10)) (ok 1) (err \"Out of bounds: end\")))\n  (let ((temp1 (fold subs1 source \n                  {start: start, end: end, cursor: 1, data: \"\"})))\n   (let ((data (get data temp1))) \n       data))))\n    \n;; Call the function to extract the substring between the bounds:\n\n;; (subs \"123456789\" 2 5)\n\n(define-read-only (subs1 \n                    (ch (buff 1))\n                    (acc {data: (buff 10), \n                          start: int,\n                          end: int,\n                          cursor: int})) \n  (let ((data (get data acc))\n        (start (get start acc))\n        (cursor (get cursor acc))\n        (end (get end acc)))                                     \n    (let ((temp2 \n           {cursor: (+ 1 cursor),\n            data: (default-to \"\"\n                     (as-max-len?\n                       (concat data \n                         (if (let ((temp3 start)\n                                   (temp4 cursor)\n                                   (temp5 end))\n                              (and (<= temp3 temp4)\n                               (<= temp4 temp5)))\n                           ch \n                           \"\"))\n                       u10))}))\n     {start: (get start acc),\n      end: (get end acc),\n      cursor: (get cursor temp2),\n      data: (get data temp2)})))\n"
      }
    },
    {
      "tx_id": "0x66df10d99d3a26018f521d60e9f744b083386c73e47ad39c394d570abee55f1f",
      "tx_status": "pending",
      "tx_type": "smart_contract",
      "receipt_time": 1598230066,
      "receipt_time_iso": "2020-08-24T00:47:46.000Z",
      "fee_rate": "2000",
      "sender_address": "ST1FJGMWPGM1P7N0K3N9QEPZK5H1VDC5YWTVMEAZ1",
      "sponsored": false,
      "post_condition_mode": "deny",
      "post_conditions": [],
      "anchor_mode": "any",
      "smart_contract": {
        "contract_id": "ST1FJGMWPGM1P7N0K3N9QEPZK5H1VDC5YWTVMEAZ1.contract-hook-1598230054238",
        "source_code": "(define-read-only (subs1 \n                    (ch (buff 1))\n                    (acc {data: (buff 10), \n                          start: int,\n                          end: int,\n                          cursor: int}))\n (begin\n  (unwrap-panic (if (and (<= 1 (get start acc)) (<= (get start acc) 10)) (ok 1) (err \"Out of bounds: start\")))\n  (unwrap-panic (if (and (<= 1 (get end acc)) (<= (get end acc) 10)) (ok 1) (err \"Out of bounds: end\")))\n  (unwrap-panic (if (and (<= 1 (get cursor acc)) (<= (get cursor acc) 10)) (ok 1) (err \"Out of bounds: cursor\")))\n  (let ((data (get data acc))\n        (start (get start acc))\n        (cursor (get cursor acc))\n        (end (get end acc)))                                     \n    (let ((temp1 \n           {cursor: (+ 1 cursor),\n            data: (default-to \"\"\n                     (as-max-len?\n                       (concat data \n                         (if (let ((temp2 start)\n                                   (temp3 cursor)\n                                   (temp4 end))\n                              (and (<= temp2 temp3)\n                               (<= temp3 temp4)))\n                           ch \n                           \"\"))\n                       u10))}))\n     {start: (get start acc),\n      end: (get end acc),\n      cursor: (get cursor temp1),\n      data: (get data temp1)}))))\n"
      }
    },
    {
      "tx_id": "0x7402d8e52204d6c8cba7465e159e79750338c3ee31d4fe6ddef1d4d226304b65",
      "nonce": 1,
      "fee_rate": "227",
      "sender_address": "SP1HJDP35SSMYP98CG8SHMYHMZDK0A495ZCH6ARYS",
      "sponsored": false,
      "post_condition_mode": "deny",
      "post_conditions": [
        {
          "type": "stx",
          "condition_code": "sent_equal_to",
          "amount": "88884500",
          "principal": {
            "type_id": "principal_standard",
            "address": "SP2J6HSSDYSTM71S0K0KK4YWRKX59JN1AD52M4B59"
          }
        }
      ],
      "anchor_mode": "any",
      "tx_status": "pending",
      "receipt_time": 1626286631,
      "receipt_time_iso": "2021-07-14T18:17:11.000Z",
      "tx_type": "contract_call",
      "contract_call": {
        "contract_id": "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.send-many-memo",
        "function_name": "send-many",
        "function_signature": "(define-public (send-many (recipients (list 200 (tuple (memo (buff 34)) (to principal) (ustx uint))))))",
        "function_args": [
          {
            "hex": "0x0b000000010c00000003046d656d6f020000000e357a62597346716a52336d736b7102746f0516b734e97043840503dc1091661c105d32b7c5c75d047573747801000000000000000000000000054c4514",
            "repr": "(list (tuple (memo 0x357a62597346716a52336d736b71) (to SP2VK9TBG8E20A0YW228PC70GBMSBFHE7BNVMKB57) (ustx u88884500)))",
            "name": "recipients",
            "type": "(list 200 (tuple (memo (buff 34)) (to principal) (ustx uint)))"
          }
        ]
      }
    }
  ]
}

=== hirosystems/stacks-blockchain-api/docs/api/blocks/get-nakamoto-blocks.example.json
{
  "limit": 1,
  "offset": 0,
  "total": 21707,
  "results": [
    {
      "canonical": true,
      "height": 21698,
      "hash": "0x9be3e38eab9c7d094fd51792383c66706838d6392e95bc05cc730b8f7520e352",
      "parent_block_hash": "0x76ee36d1d6c88e56b5c0e80f0d7bc7d3492141faf1b900efb19fcd00457d4654",
      "burn_block_time": 1626281749,
      "burn_block_time_iso": "2021-07-14T16:55:49.000Z",
      "burn_block_hash": "0x0000000000000000000ea16f8e906e85ee1cb4dff1e5424e93843b3cec8b0bcb",
      "burn_block_height": 691014,
      "miner_txid": "0x118f7122a69441d13e6a3dfd4c3b0f9950be25195bb8126aae7fadea1aa9185d",
      "txs": [
        "0x76f58b2eaff65a07a5971b241c4e71fee92ee0f9396809f911f90839f9004cac",
        "0x32972d9052b068f218f6e13451f7aff937099b74bbf95fac7d9402295b1b3941",
        "0x8cd30724c02a9cc1d8879a34dc136ebfdb2008420badcfb5947b92f85ebce79b",
        "0xf5c1577f42d3753a508101e045dd2dc60491eb0aa552e0ecd0ad37cc697143f4",
        "0x35e4c20e2838f999e0cf0b40c5fabce154c2df1912a1074150d26784c53f7a20",
        "0x501eb42b82e5b7a7350b47fa143cd4e90bb46d43e4a7d22830b2bf2aa70b7922"
      ]
    }
  ]
}
