=== hirosystems/stacks-blockchain-api/docs/api/tokens/get-non-fungible-token-history.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "List of Non-Fungible Token history events",
  "title": "NonFungibleTokenHistoryEventList",
  "type": "object",
  "required": [
    "results",
    "limit",
    "offset",
    "total"
  ],
  "additionalProperties": false,
  "properties": {
    "limit": {
      "type": "integer",
      "maximum": 200,
      "description": "The number of events to return"
    },
    "offset": {
      "type": "integer",
      "description": "The number to events to skip (starting at `0`)"
    },
    "total": {
      "type": "integer",
      "description": "The number of events available"
    },
    "results": {
      "type": "array",
      "items": {
        "$ref": "../../entities/tokens/non-fungible-token-history-event.schema.json"
      }
    }
  }
}

=== hirosystems/stacks-blockchain-api/docs/api/address/get-address-transactions-with-transfers.example.json
{
  "limit": 20,
  "offset": 0,
  "total": 2,
  "results": [
    {
      "tx": {
        "tx_id": "0x34d79c7cfc2fe525438736733e501a4bf0308a5556e3e080d1e2c0858aad7448",
        "tx_type": "contract_call",
        "nonce": 11,
        "fee_rate": "346",
        "sender_address": "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE",
        "sponsored": false,
        "post_condition_mode": "deny",
        "tx_status": "success",
        "block_hash": "0x13d1b4ad35c95bca209397420fb8af104d2929d91993ba056d7a1ca5470095f9",
        "block_height": 3246,
        "burn_block_time": 1613009951,
        "burn_block_time_iso": "2021-02-11T02:19:11.000Z",
        "canonical": true,
        "is_unanchored": false,
        "microblock_hash": "0x590a1bb1d7bcbeafce0a9fc8f8a69e369486192d14687fe95fbe4dc1c71d49df",
        "microblock_sequence": 5,
        "microblock_canonical": true,
        "tx_index": 1,
        "tx_result": {
          "hex": "0x0703",
          "repr": "(ok true)"
        },
        "post_conditions": [
          {
            "type": "stx",
            "condition_code": "sent_equal_to",
            "amount": "350",
            "principal": {
              "type_id": "principal_standard",
              "address": "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE"
            }
          }
        ],
        "contract_call": {
          "contract_id": "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.send-many-memo",
          "function_name": "send-many",
          "function_signature": "(define-public (send-many (recipients (list 200 (tuple (memo (buff 34)) (to principal) (ustx uint))))))",
          "function_args": [
            {
              "hex": "0x0b000000020c00000003046d656d6f020000000966697273746d656d6f02746f05168c031b2db5895ece0cdfbf76e0b0e8af67226a6f047573747801000000000000000000000000000000960c00000003046d656d6f020000000a7365636f6e646d656d6f02746f05168974da696d74a16d0955bc8e55720dfd39e789cf047573747801000000000000000000000000000000c8",
              "repr": "(list (tuple (memo 0x66697273746d656d6f) (to SP26066SDPP4NXKGCVYZQDR5GX2QPE8KADZ0YK2J7) (ustx u150)) (tuple (memo 0x7365636f6e646d656d6f) (to SP24Q9PK9DNTA2V89APY8WNBJ1QYKKSW9SWB04RJP) (ustx u200)))",
              "name": "recipients",
              "type": "(list 200 (tuple (memo (buff 34)) (to principal) (ustx uint)))"
            }
          ]
        },
        "events": [],
        "event_count": 4
      },
      "stx_sent": "696",
      "stx_received": "0",
      "stx_transfers": [
        {
          "amount": "200",
          "sender": "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE",
          "recipient": "SP24Q9PK9DNTA2V89APY8WNBJ1QYKKSW9SWB04RJP"
        },
        {
          "amount": "150",
          "sender": "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE",
          "recipient": "SP26066SDPP4NXKGCVYZQDR5GX2QPE8KADZ0YK2J7"
        }
      ],
      "ft_transfers": [
        {
          "amount": "103",
          "asset_identifier": "SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-token::miamicoin",
          "sender": "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE",
          "recipient": "SP24Q9PK9DNTA2V89APY8WNBJ1QYKKSW9SWB04RJP"
        }
      ],
      "nft_transfers": [
        {
          "asset_identifier": "SP497E7RX3233ATBS2AB9G4WTHB63X5PBSP5VGAQ.boom-nfts::boom",
          "value": { "hex": "0x00", "repr": "0" },
          "sender": "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE",
          "recipient": "SP24Q9PK9DNTA2V89APY8WNBJ1QYKKSW9SWB04RJP"
        }
      ]
    },
    {
      "tx": {
        "tx_id": "0x628045bff13658396277d618e9a3e4d468a4b3876eff4941d2f13ed88cd7abb7",
        "tx_type": "token_transfer",
        "nonce": 8,
        "fee_rate": "180",
        "sender_address": "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE",
        "sponsored": false,
        "post_condition_mode": "deny",
        "tx_status": "success",
        "block_hash": "0x2b8599696f64e2456c67b1ab5e63078f99d87bd1d903c37fdcfd73b1890a7551",
        "block_height": 1761,
        "burn_block_time": 1611968237,
        "burn_block_time_iso": "2021-01-30T00:57:17.000Z",
        "canonical": true,
        "is_unanchored": false,
        "microblock_hash": "",
        "microblock_sequence": 2147483647,
        "microblock_canonical": true,
        "tx_index": 2,
        "tx_result": {
          "hex": "0x0703",
          "repr": "(ok true)"
        },
        "token_transfer": {
          "recipient_address": "SPRSM0R2JZWBCZ39NQBARWTMX9TE99K3JK8D5KMX",
          "amount": "100000",
          "memo": "0x57656c636f6d6520746f20426f6f6d2e000000000000000000000000000000000000"
        },
        "events": [],
        "event_count": 1
      },
      "stx_sent": "100180",
      "stx_received": "0",
      "stx_transfers": [
        {
          "amount": "100000",
          "sender": "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE",
          "recipient": "SPRSM0R2JZWBCZ39NQBARWTMX9TE99K3JK8D5KMX"
        }
      ],
      "ft_transfers": [],
      "nft_transfers": []
    }
  ]
}

=== hirosystems/stacks-blockchain-api/docs/api/blocks/get-burn-blocks.example.json
{
  "limit": 1,
  "offset": 0,
  "total": 21707,
  "results": [
    {
      "burn_block_time": 1626281749,
      "burn_block_time_iso": "2021-07-14T16:55:49.000Z",
      "burn_block_hash": "0x0000000000000000000ea16f8e906e85ee1cb4dff1e5424e93843b3cec8b0bcb",
      "burn_block_height": 691014,
      "stacks_blocks_count": 10
    }
  ]
}

=== hirosystems/stacks-blockchain-api/docs/api/burnchain/get-reward-slot-holders.example.json
{
  "limit": 20,
  "offset": 0,
  "total": 2,
  "results": [
    {
        "canonical": true,
        "burn_block_hash": "0x4eaabcd105865e471f697eff5dd5bd85d47ecb5a26a3379d74fae0ae87c40904",
        "burn_block_height": 331,
        "address": "1C56LYirKa3PFXFsvhSESgDy2acEHVAEt6",
        "slot_index": 0
    },
    {
      "canonical": true,
      "burn_block_hash": "0x4eaabcd105865e471f697eff5dd5bd85d47ecb5a26a3379d74fae0ae87c40904",
      "burn_block_height": 331,
      "address": "1M3bvWB9CRh5BTumeVxtHDEV6W4S2R9AZw",
      "slot_index": 0
    }
  ]
}

=== hirosystems/stacks-blockchain-api/docs/api/stacking/get-pox-cycle-signers.example.json
{
  "limit": 20,
  "offset": 0,
  "total": 3,
  "results": [
    {
      "signing_key": "0x038e3c4529395611be9abf6fa3b6987e81d402385e3d605a073f42f407565a4a3d",
      "signer_address": "STRYYQQ9M8KAF4NS7WNZQYY59X93XEKR31JP64CP",
      "stacked_amount": "686251350000000000",
      "stacked_amount_percent": 50,
      "weight": 5,
      "weight_percent": 55.55555555555556,
      "solo_stacker_count": 16,
      "pooled_stacker_count": 3615
    },
    {
      "signing_key": "0x029874497a7952483aa23890e9d0898696f33864d3df90939930a1f45421fe3b09",
      "signer_address": "STF9B75ADQAVXQHNEQ6KGHXTG7JP305J2GRWF3A2",
      "stacked_amount": "457500900000000000",
      "stacked_amount_percent": 33.333333333333336,
      "weight": 3,
      "weight_percent": 33.33333333333333,
      "solo_stacker_count": 0,
      "pooled_stacker_count": 1456
    },
    {
      "signing_key": "0x02dcde79b38787b72d8e5e0af81cffa802f0a3c8452d6b46e08859165f49a72736",
      "signer_address": "ST18MDW2PDTBSCR1ACXYRJP2JX70FWNM6YY2VX4SS",
      "stacked_amount": "228750450000000000",
      "stacked_amount_percent": 16.666666666666668,
      "weight": 1,
      "weight_percent": 11.11111111111111,
      "solo_stacker_count": 637,
      "pooled_stacker_count": 0
    }
  ]
}

=== hirosystems/stacks-blockchain-api/docs/api/stacking/get-pox-cycles.example.json
{
  "limit": 20,
  "offset": 0,
  "total": 3,
  "results": [
    {
      "block_height": 50,
      "cycle_number": 14,
      "index_block_hash": "0xf5be33abc4e508bdaf2191e88339372edcb3358c44e2a31e1b9b44f2880dde09",
      "total_signers": 3,
      "total_stacked_amount": "1372502700000000000",
      "total_weight": 9
    },
    {
      "block_height": 22,
      "cycle_number": 13,
      "index_block_hash": "0x5077c7d971dd83cd3ba19dca579e3cc8dcf17913186b66093c94520e50d3b7b2",
      "total_signers": 3,
      "total_stacked_amount": "1372502700000000000",
      "total_weight": 9
    },
    {
      "block_height": 13,
      "cycle_number": 12,
      "index_block_hash": "0x62d06851fe03f17cb45a488ae70bd8e0c5c308c523f37814ad4df36bd2108713",
      "total_signers": 3,
      "total_stacked_amount": "1372502700000000000",
      "total_weight": 9
    }
  ]
}

=== hirosystems/stacks-blockchain-api/docs/api/transaction/get-transactions.example.json
{
  "limit": 10,
  "offset": 0,
  "total": 101922,
  "results": [
    {
      "tx_id": "0x20dedbef812e44d712569224411b27324b68ab4667321a4badd5e81ba76bf0eb",
      "nonce": 269,
      "fee_rate": "0",
      "sender_address": "SPQXK10DBF5ECAM30XVE3EJA8DNZF3VE0BK4MKV",
      "sponsored": false,
      "post_condition_mode": "deny",
      "post_conditions": [],
      "anchor_mode": "on_chain_only",
      "is_unanchored": false,
      "block_hash": "0x28a9e2749b82bdc058776781a5abd5c9a6efed38f05545a8a51152655b8e1f4b",
      "parent_block_hash": "0x3789b75ccfe7f2acf85c3f069fd5b8f95f73aba5332fa618243957d1c017a2a3",
      "block_height": 21709,
      "burn_block_height": 51396,
      "burn_block_time": 1626286436,
      "burn_block_time_iso": "2021-07-14T18:13:56.000Z",
      "canonical": true,
      "tx_index": 0,
      "tx_status": "success",
      "tx_result": {
        "hex": "0x0703",
        "repr": "(ok true)"
      },
      "microblock_hash": "",
      "microblock_sequence": 2147483647,
      "microblock_canonical": true,
      "event_count": 0,
      "events": [],
      "tx_type": "coinbase",
      "coinbase_payload": {
        "data": "0x0000000000000000000000000000000000000000000000000000000000000000"
      }
    }
  ]
}
