=== hirosystems/stacks-blockchain-api/docs/entities/tokens/non-fungible-token-mint-1-tx-metadata.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "NonFungibleTokenMintWithTxMetadata",
  "description": "Non-Fungible Token mint event with transaction metadata",
  "required": ["event_index", "value", "tx"],
  "additionalProperties": false,
  "properties": {
    "recipient": {
      "type": "string"
    },
    "event_index": {
      "type": "integer"
    },
    "value": {
      "type": "object",
      "required": ["hex", "repr"],
      "description": "Non-Fungible Token value",
      "additionalProperties": false,
      "properties": {
        "hex": {
          "type": "string",
          "description": "Hex string representing the identifier of the Non-Fungible Token"
        },
        "repr": {
          "type": "string",
          "description": "Readable string of the Non-Fungible Token identifier"
        }
      }
    },
    "tx": {
      "$ref": "../transactions/transaction.schema.json"
    }
  }
}

=== hirosystems/stacks-blockchain-api/docs/entities/tokens/non-fungible-token-mint-1-tx-metadata.example.schema.json
{
  "recipient": "SP25KJH4N4YNKTVXSWSHDPVCWDFAN2BA4H2VQVN0G",
  "event_index": 1,
  "value": {
    "hex": "0x01000000000000000000000000000009c7",
    "repr": "u2503"
  },
  "tx": {
    "tx_id": "0xd5c199447bc5f08d1821350455f4c103ad769976c7a6b745182782d53b5c7922",
    "nonce": 4,
    "fee_rate": "81200",
    "sender_address": "SP25KJH4N4YNKTVXSWSHDPVCWDFAN2BA4H2VQVN0G",
    "sponsored": false,
    "post_condition_mode": "deny",
    "post_conditions": [
      {
        "type": "stx",
        "condition_code": "sent_equal_to",
        "amount": "100000000",
        "principal": {
          "type_id": "principal_standard",
          "address": "SP25KJH4N4YNKTVXSWSHDPVCWDFAN2BA4H2VQVN0G"
        }
      }
    ],
    "anchor_mode": "any",
    "is_unanchored": false,
    "block_hash": "0xde60b4b100b1828dc6383db869b1e051fe68ac3fb0a72fffaae1b18af3e3c675",
    "parent_block_hash": "0xe90233fb36b6a932de91af1b030723ca71335eed7b0792f2c382a827beb5c2f3",
    "block_height": 36777,
    "burn_block_time": 1636213080,
    "burn_block_time_iso": "2021-11-06T15:38:00.000Z",
    "parent_burn_block_time": 1636211530,
    "parent_burn_block_time_iso": "2021-11-06T15:12:10.000Z",
    "canonical": true,
    "tx_index": 11,
    "tx_status": "success",
    "tx_result": {
      "hex": "0x0701000000000000000000000000000009c7",
      "repr": "(ok u2503)"
    },
    "microblock_hash": "",
    "microblock_sequence": 2147483647,
    "microblock_canonical": true,
    "event_count": 2,
    "events": [],
    "execution_cost_read_count": 14,
    "execution_cost_read_length": 91190,
    "execution_cost_runtime": 92297000,
    "execution_cost_write_count": 3,
    "execution_cost_write_length": 19,
    "tx_type": "contract_call",
    "contract_call": {
      "contract_id": "SP2X0TZ59D5SZ8ACQ6YMCHHNR2ZN51Z32E2CJ173.the-explorer-guild-mint",
      "function_name": "claim",
      "function_signature": "(define-public (claim ))"
    }
  }
}
